[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gobs"
name = "Peglin_Relic_Pack"
versionNumber = "2.0.2"
description = "A Collection of Peglin Relics created with Relic Lib. Meant to be a sample for creating custom relics."
websiteUrl = "https://github.com/crazyjackel/Peglin-RelicPack"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1901"
Gobs-Peglin_Relic_Library = "2.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[[build.copy]]
source = "Include"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []
